apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  labels:
    app: url-shortener
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://postgres:securepassword@postgres-service:5432/url_shortener"
  REDIS_URL: "redis://redis-0.redis:6379/0"
